# 01 – Market Discovery & Triad Selection

Browse Polymarket categories, inspect candidate markets, and finalise the
**base / similar / dissimilar** triad for Stage 1.

In [1]:
import sys, pathlib, logging
sys.path.insert(0, str(pathlib.Path.cwd().parent))
logging.basicConfig(level=logging.INFO)

from src.collect.discovery import fetch_tags, fetch_markets_by_tag, fetch_all_markets, build_triad_config
import pandas as pd
pd.set_option("display.max_colwidth", 80)

## 1. Fetch available tags (categories)

In [2]:
tags_df = fetch_tags()
tags_df.head(30)

INFO:src.client:Saved raw JSON → /Users/hetp/Documents/UWaterloo/4B/SYDE 532/Project/data/raw/tags.json
INFO:src.collect.discovery:Fetched 100 tags

,id,label,slug,publishedAt,createdAt,updatedAt,requiresTranslation,forceShow,isCarousel,updatedBy,forceHide
0,671,jto,jto,2023-12-07 19:16:45.979+00,2023-12-07T19:16:45.993Z,2026-02-06T20:01:39.282804Z,False,NaN,NaN,NaN,NaN
1,101592,Tom Aspinal,tom-aspinal,NaN,2024-12-31T19:48:27.938591Z,2026-02-06T20:01:39.296759Z,False,NaN,NaN,NaN,NaN
2,101115,Preston,preston,NaN,2024-10-28T20:41:17.828152Z,2026-02-06T20:01:39.322562Z,False,NaN,NaN,NaN,NaN
3,746,detroit pistons,detroit-pistons,2023-12-18 18:24:38.687+00,2023-12-18T18:24:38.708Z,2026-02-06T20:01:39.323344Z,False,NaN,NaN,NaN,NaN
4,1493,spider-man,spider-man,2024-02-27 19:31:50.152+00,2024-02-27T19:31:50.171Z,2026-02-06T20:01:39.389634Z,False,NaN,NaN,NaN,NaN
5,1564,facebook,facebook,2024-03-05 16:50:42.451+00,2024-03-05T16:50:44.559Z,2026-02-06T20:01:39.417037Z,False,NaN,NaN,NaN,NaN
6,335,peace deals,peace-deals,2023-11-02 21:56:32.239+00,2023-11-02T21:56:32.251Z,2026-02-06T20:01:39.417937Z,False,NaN,NaN,NaN,NaN
7,103019,Somali,somali,NaN,2025-12-27T22:45:41.115947Z,2026-02-06T20:01:39.420361Z,False,NaN,NaN,NaN,NaN
8,103082,Jungleman,jungleman,NaN,2026-01-07T19:02:07.001529Z,2026-02-06T20:01:39.421154Z,False,NaN,NaN,NaN,NaN
9,680,pudgy penguins,pudgy-penguins,2023-12-08 16:34:57.542+00,2023-12-08T16:34:57.547Z,2026-02-06T20:01:39.42202Z,False,NaN,NaN,NaN,NaN
10,103061,mag 7,mag-7,NaN,2026-01-05T19:17:58.621353Z,2026-02-06T20:01:39.422725Z,False,NaN,NaN,NaN,NaN
11,100397,fivethrityeight,fivethrityeight,NaN,2024-08-28T22:05:20.893571Z,2026-02-06T20:01:39.423546Z,False,NaN,NaN,NaN,NaN
12,102787,prop,prop,NaN,2025-10-30T21:06:03.144996Z,2026-02-06T20:01:39.455764Z,False,NaN,NaN,NaN,NaN
13,311,trade,trade,2023-11-02 21:53:18.067+00,2023-11-02T21:53:18.166Z,2026-02-06T20:01:39.485138Z,False,NaN,NaN,NaN,NaN
14,100787,CONMEBOL,conmebol,NaN,2024-10-09T22:08:44.396352Z,2026-02-06T20:01:39.485792Z,False,NaN,NaN,NaN,NaN
15,101094,Hawaii,hawaii,NaN,2024-10-25T19:28:02.991592Z,2026-02-06T20:01:39.531179Z,False,NaN,NaN,NaN,NaN
16,100545,slotkin,slotkin,NaN,2024-09-19T21:57:29.844648Z,2026-02-06T20:01:39.556477Z,False,NaN,NaN,NaN,NaN
17,1510,minnesota,minnesota,2024-02-28 22:12:58.233+00,2024-02-28T22:13:00.833Z,2026-02-06T20:01:39.569996Z,False,NaN,NaN,NaN,NaN
18,100810,Perfect Timing,perfect-timing,NaN,2024-10-11T16:04:38.492954Z,2026-02-06T20:01:39.570616Z,False,NaN,NaN,NaN,NaN
19,100354,Speed,speed,NaN,2024-08-21T23:09:44.65522Z,2026-02-06T20:01:39.571401Z,False,NaN,NaN,NaN,NaN
20,103058,Test1,test1,NaN,2026-01-05T13:19:10.183265Z,2026-02-06T20:01:39.571942Z,False,False,False,NaN,NaN
21,101414,Checo Perez,checo-perez,NaN,2024-12-03T18:01:36.597699Z,2026-02-06T20:02:41.693207Z,False,NaN,NaN,NaN,NaN
22,1619,khalifa sall,khalifa-sall,2024-03-11 22:25:22.168+00,2024-03-11T22:25:24.232Z,2026-02-06T20:02:41.694287Z,False,NaN,NaN,NaN,NaN
23,101451,Joaquin Buckley,joaquin-buckley,NaN,2024-12-09T23:02:30.506209Z,2026-02-06T20:02:41.695115Z,False,NaN,NaN,NaN,NaN
24,724,charts,charts,2023-12-12 21:00:40.197+00,2023-12-12T21:00:40.201Z,2026-02-06T20:02:41.695781Z,False,NaN,NaN,NaN,NaN
25,45,trail blazers,trail-blazers,2023-11-02 21:13:49.657+00,2023-11-02T21:13:49.664Z,2026-02-06T20:02:41.696437Z,False,NaN,NaN,NaN,NaN
26,101994,NL Central,nl-central,NaN,2025-03-25T22:33:44.61249Z,2026-02-06T20:02:41.697134Z,False,NaN,NaN,NaN,NaN
27,103174,robert Fico,robert-fico,NaN,2026-01-16T18:15:48.870744Z,2026-02-06T20:02:41.697973Z,False,NaN,NaN,NaN,NaN
28,100999,Benfica,benfica,NaN,2024-10-21T22:35:02.808325Z,2026-02-06T20:02:41.698673Z,False,NaN,NaN,NaN,NaN
29,101003,Slovan Bratislava,slovan-bratislava,NaN,2024-10-21T22:56:34.938223Z,2026-02-06T20:02:41.699411Z,False,NaN,NaN,NaN,NaN

## 2. Browse markets by category

Adjust the `tag_slug` below to explore different categories.
Look for markets with **high volume**, **high liquidity**, and a
**future end date** (so the price series is still growing).

In [3]:
# Political markets
politics_df = fetch_markets_by_tag("politics")
politics_df[["question", "slug", "condition_id", "clob_token_yes", "end_date", "volume", "liquidity"]].head(20)

INFO:src.client:Saved raw JSON → /Users/hetp/Documents/UWaterloo/4B/SYDE 532/Project/data/raw/markets_politics.json
INFO:src.collect.discovery:Fetched 50 markets for tag 'politics' (top volume: 9897463)

,question,slug,condition_id,clob_token_yes,end_date,volume,liquidity
0,Will Vivek Ramaswamy win the 2028 Republican presidential nomination?,will-vivek-ramaswamy-win-the-2028-republican-presidential-nomination,0xd997dc2a212a7d6673375a3b016db1fb214247142f8cde0cbf07f8e6d789877c,7847177314809025001842027337093046201021185723933452855314998541165696902642,2028-11-07T00:00:00Z,9.897463e+06,538674.00119
1,Will Delcy Rodríguez be the leader of Venezuela end of 2026?,will-delcy-rodrguez-be-the-leader-of-venezuela-end-of-2026,0xa01d48a973e40770719dab42faf1aeae5da4376d9eca46e77265c7551d1be0f7,38667196958602416137463628517439560119304765709104570192447644733106171420112,2026-12-31T00:00:00Z,9.911116e+05,27441.12720
2,Will The Weeknd have the greatest number of monthly Spotify listeners this m...,will-the-weeknd-have-the-greatest-number-of-monthly-spotify-listeners-this-m...,0xe8ec9fb94e2c3c30a53bd6cddd5ed0818430576c109028ec04ea6fe47ec16ffd,72215495808962882442227957504397899994205027071946858683339872158649978621745,2026-02-28T00:00:00Z,9.997987e+04,5858.05711
3,"Grok 5 released by March 31, 2026?",grok-5-released-by-march-31-2026,0xb7b4b48d233d854fa0793bb3ac3da246bd7863e6039300b61df035125fe4f581,111199335102802129986385434826729904605097886098325344211061360860214628320521,NaN,9.987279e+04,8263.88940
4,Will Silver (SI) hit (HIGH) $185 by end of February?,will-silver-si-hit-high-185-by-end-of-february-694-754,0x8eebd379d1fd9d12f58e0a97c2aae73f1e1fd0c92c31b59275fc3645b1597f87,3132591794760264995577925527621672916339864017285721439131771940573384623848,2026-02-28T00:00:00Z,9.962033e+04,158741.57036
5,Nuclear weapon detonation by March 31?,nuclear-weapon-detonation-by-march-31,0x4afb076c5d9dfe1c33bf300cfd9fb93a5a8d9bfce8fe2beaeccbde5f8c269fc1,83745161536963539374758363997483220394665712527717501198935570938573276596563,2026-03-31T00:00:00Z,9.932240e+04,8778.14312
6,Will Japan’s January 2026 unemployment rate be ≤2.1%?,will-japans-january-2026-unemployment-rate-be-2pt1,0xd822ccf5f9325363598c8a47bd8e1f7f5c4ee2bd05106317e1524cc16a3a9f95,84909634827707129486900371878355483917943245288000191120896879062473383973290,2026-03-03T00:00:00Z,9.896720e+04,240.58162
7,Kings vs. Blue Jackets: O/U 6.5,nhl-lak-cbj-2026-01-26-total-6pt5,0x203511b34fa55670a3d65b460e912652fdd4255258828b266b3da45c84521acf,69506504769963901283918727206455219450062789028070087224654077420495427804288,2026-01-27T00:00:00Z,9.999917e+03,135.84960
8,Will Morocco win Group C in the 2026 FIFA World Cup?,will-morocco-win-group-c-in-the-2026-fifa-world-cup,0xcd82ced289c1009bb08ea7d74cdc4c56d7e3feaf4eebafa429e04d8d08ba8eb6,9993362623254508594982212570716155560975868718584876749669600087469425428671,2026-06-27T00:00:00Z,9.996884e+03,3427.00730
9,"Will ""Sinners"" win exactly 5 awards at the Oscars?",will-sinners-win-exactly-5-awards-at-the-oscars,0xad8e66948595968c5eb29fbda0c805ea53a0f45e00310f07b10c7e7681027c04,79490522542250943082390022419364604163533005858719367745573112352656937744621,2026-03-15T00:00:00Z,9.978144e+03,3343.46750
10,Will CR win the most seats in the 2026 Colombian Chamber of Representatives ...,will-cr-win-the-most-seats-in-the-2026-colombian-chamber-of-representatives-...,0x4a48f9a1e2cd2a274ff636ba53326479cafad09e21ce526aa7b07e3add67575a,69539866920971893324539701255733985995005298853448247993841542507119576740580,2026-03-08T20:00:00Z,9.977751e+03,6163.84318
11,New Zealand Breakers vs. Cairns Taipans,bknbl-new-cai-2026-02-19,0xe01dfa0612a80d56eae85d911e89cd98cde1d0f6717c0e583b5a6d5a29d4ad64,78892455310794078214292476247012110024049050529854661365916968305741151792952,2026-02-26T06:30:00Z,9.974423e+03,1173.24140
12,US seizes an Iran-linked oil tanker by Feb 28?,us-seizes-an-iran-linked-oil-tanker-by-feb-28,0xa32bd28c0c288da3ddf21b34f6a86679c2ae81232f03441df6b9eff63d16a6cf,105509773956777725100823655243528621611068096678262325758329096120271236435431,2026-02-28T00:00:00Z,9.961374e+03,3071.65780
13,Will Janez Janša be the next Prime Minister of Slovenia?,will-janez-jana-be-the-next-prime-minister-of-slovenia,0xe94749bbf616139120735f9720de5b1a94b61cb7da0feb633f97f113d61a167b,82530627405409911305927805635950267430246838540555305041705674192961973127302,2026-03-22T00:00:00Z,9.960947e+03,6489.53840
14,"Will the US next strike Iran during the week of February 15-21, 2026 (ET)?",will-the-us-next-strike-iran-during-the-week-of-february-15-21-2026-et,0x6395cbd98104c532b1a74470f0f0b2e765ca740bbc623d5f04fbf282e6fe3652,77944431976570712623048042703776067647183345723044716065978734139522523537860,2026-04-04T00:00:00Z,9.958677e+03,3039.13760
15,Will the Los Angeles Clippers finish as the #1 seed in the 2025–2026 NBA Wes...,will-the-los-angeles-clippers-finish-as-the-1-seed-in-the-20252026-nba-weste...,0xe05794ccced6b2687a43502896ec8bbb1a7efd26f05adc88edc96916a6d92475,103365321044546830351586566069038719229016365199771829748333033747738176327765,2026-04-12T00:00:00Z,9.953652e+03,22078.19736
16,Will Elon Musk post 1360-1399 tweets in March 2026?,elon-musk-of-tweets-march-2026-1360-1399,0x044f3ae5fdf246b4b5f8ff4233cea15c083932cd019bc25410d027b87a927df7,77834041247353940463018240476424059627370749493122205515409543524601837582710,2026-04-01T04:00:00Z,9.944945e+03,10206.01450
17,Will MrBeast hit 477 Million subscribers by March 31?,will-mrbeast-hit-477-million-subscribers-by-march-31-246-645,0xf5dad4c302a8e5a52730171d0f3928c69982726da53375ddf260e7269df96ae5,48500566029691014494538715409643159805481226449050858904270561683848714742810,2026-03-31T00:00:00Z,9.944768e+03,5175.12810
18,Bank of England decreases interest rates by 25 bps after March 2026 meeting?,bank-of-england-decreases-interest-rates-by-25-bps-after-march-2026-meeting-384,0xb2e1fde8d5b6d178509efb34b3850c69a7bc742c361ba6016054e50302f833c7,22090835838074327391045821864169112707760835582772637183872923635041881148116,2026-03-19T00:00:00Z,9.938091e+03,5781.46630
19,Will Jimmy Butler win the 2025–2026 NBA Clutch Player of the Year?,nba-2025-26-clutch-player-of-the-year-jimmy-butler,0x4d9dc5a7e516dcec935b0381707ccd4c52d1e73fe8d90307ec8309e4728551c8,93287580662612374998000503364773686496854653048711183445257002067443625560147,2026-06-30T00:00:00Z,9.937853e+03,1218.54960

In [4]:
# Sports markets
sports_df = fetch_markets_by_tag("sports")
sports_df[["question", "slug", "condition_id", "clob_token_yes", "end_date", "volume", "liquidity"]].head(20)

INFO:src.client:Saved raw JSON → /Users/hetp/Documents/UWaterloo/4B/SYDE 532/Project/data/raw/markets_sports.json
INFO:src.collect.discovery:Fetched 50 markets for tag 'sports' (top volume: 9897463)

,question,slug,condition_id,clob_token_yes,end_date,volume,liquidity
0,Will Vivek Ramaswamy win the 2028 Republican presidential nomination?,will-vivek-ramaswamy-win-the-2028-republican-presidential-nomination,0xd997dc2a212a7d6673375a3b016db1fb214247142f8cde0cbf07f8e6d789877c,7847177314809025001842027337093046201021185723933452855314998541165696902642,2028-11-07T00:00:00Z,9.897463e+06,538674.00119
1,Will Delcy Rodríguez be the leader of Venezuela end of 2026?,will-delcy-rodrguez-be-the-leader-of-venezuela-end-of-2026,0xa01d48a973e40770719dab42faf1aeae5da4376d9eca46e77265c7551d1be0f7,38667196958602416137463628517439560119304765709104570192447644733106171420112,2026-12-31T00:00:00Z,9.911116e+05,27441.12720
2,Will The Weeknd have the greatest number of monthly Spotify listeners this m...,will-the-weeknd-have-the-greatest-number-of-monthly-spotify-listeners-this-m...,0xe8ec9fb94e2c3c30a53bd6cddd5ed0818430576c109028ec04ea6fe47ec16ffd,72215495808962882442227957504397899994205027071946858683339872158649978621745,2026-02-28T00:00:00Z,9.997987e+04,5858.05711
3,"Grok 5 released by March 31, 2026?",grok-5-released-by-march-31-2026,0xb7b4b48d233d854fa0793bb3ac3da246bd7863e6039300b61df035125fe4f581,111199335102802129986385434826729904605097886098325344211061360860214628320521,NaN,9.987279e+04,8263.88940
4,Will Silver (SI) hit (HIGH) $185 by end of February?,will-silver-si-hit-high-185-by-end-of-february-694-754,0x8eebd379d1fd9d12f58e0a97c2aae73f1e1fd0c92c31b59275fc3645b1597f87,3132591794760264995577925527621672916339864017285721439131771940573384623848,2026-02-28T00:00:00Z,9.962033e+04,158741.57036
5,Nuclear weapon detonation by March 31?,nuclear-weapon-detonation-by-march-31,0x4afb076c5d9dfe1c33bf300cfd9fb93a5a8d9bfce8fe2beaeccbde5f8c269fc1,83745161536963539374758363997483220394665712527717501198935570938573276596563,2026-03-31T00:00:00Z,9.932240e+04,8778.14312
6,Will Japan’s January 2026 unemployment rate be ≤2.1%?,will-japans-january-2026-unemployment-rate-be-2pt1,0xd822ccf5f9325363598c8a47bd8e1f7f5c4ee2bd05106317e1524cc16a3a9f95,84909634827707129486900371878355483917943245288000191120896879062473383973290,2026-03-03T00:00:00Z,9.896720e+04,240.58162
7,Kings vs. Blue Jackets: O/U 6.5,nhl-lak-cbj-2026-01-26-total-6pt5,0x203511b34fa55670a3d65b460e912652fdd4255258828b266b3da45c84521acf,69506504769963901283918727206455219450062789028070087224654077420495427804288,2026-01-27T00:00:00Z,9.999917e+03,135.84960
8,Will Morocco win Group C in the 2026 FIFA World Cup?,will-morocco-win-group-c-in-the-2026-fifa-world-cup,0xcd82ced289c1009bb08ea7d74cdc4c56d7e3feaf4eebafa429e04d8d08ba8eb6,9993362623254508594982212570716155560975868718584876749669600087469425428671,2026-06-27T00:00:00Z,9.996884e+03,3427.00730
9,"Will ""Sinners"" win exactly 5 awards at the Oscars?",will-sinners-win-exactly-5-awards-at-the-oscars,0xad8e66948595968c5eb29fbda0c805ea53a0f45e00310f07b10c7e7681027c04,79490522542250943082390022419364604163533005858719367745573112352656937744621,2026-03-15T00:00:00Z,9.978144e+03,3343.46750
10,Will CR win the most seats in the 2026 Colombian Chamber of Representatives ...,will-cr-win-the-most-seats-in-the-2026-colombian-chamber-of-representatives-...,0x4a48f9a1e2cd2a274ff636ba53326479cafad09e21ce526aa7b07e3add67575a,69539866920971893324539701255733985995005298853448247993841542507119576740580,2026-03-08T20:00:00Z,9.977751e+03,6163.84350
11,New Zealand Breakers vs. Cairns Taipans,bknbl-new-cai-2026-02-19,0xe01dfa0612a80d56eae85d911e89cd98cde1d0f6717c0e583b5a6d5a29d4ad64,78892455310794078214292476247012110024049050529854661365916968305741151792952,2026-02-26T06:30:00Z,9.974423e+03,1173.24140
12,US seizes an Iran-linked oil tanker by Feb 28?,us-seizes-an-iran-linked-oil-tanker-by-feb-28,0xa32bd28c0c288da3ddf21b34f6a86679c2ae81232f03441df6b9eff63d16a6cf,105509773956777725100823655243528621611068096678262325758329096120271236435431,2026-02-28T00:00:00Z,9.961374e+03,3472.30910
13,Will Janez Janša be the next Prime Minister of Slovenia?,will-janez-jana-be-the-next-prime-minister-of-slovenia,0xe94749bbf616139120735f9720de5b1a94b61cb7da0feb633f97f113d61a167b,82530627405409911305927805635950267430246838540555305041705674192961973127302,2026-03-22T00:00:00Z,9.960947e+03,6489.53840
14,"Will the US next strike Iran during the week of February 15-21, 2026 (ET)?",will-the-us-next-strike-iran-during-the-week-of-february-15-21-2026-et,0x6395cbd98104c532b1a74470f0f0b2e765ca740bbc623d5f04fbf282e6fe3652,77944431976570712623048042703776067647183345723044716065978734139522523537860,2026-04-04T00:00:00Z,9.958677e+03,3039.13760
15,Will the Los Angeles Clippers finish as the #1 seed in the 2025–2026 NBA Wes...,will-the-los-angeles-clippers-finish-as-the-1-seed-in-the-20252026-nba-weste...,0xe05794ccced6b2687a43502896ec8bbb1a7efd26f05adc88edc96916a6d92475,103365321044546830351586566069038719229016365199771829748333033747738176327765,2026-04-12T00:00:00Z,9.953652e+03,22078.19736
16,Will Elon Musk post 1360-1399 tweets in March 2026?,elon-musk-of-tweets-march-2026-1360-1399,0x044f3ae5fdf246b4b5f8ff4233cea15c083932cd019bc25410d027b87a927df7,77834041247353940463018240476424059627370749493122205515409543524601837582710,2026-04-01T04:00:00Z,9.944945e+03,10206.01450
17,Will MrBeast hit 477 Million subscribers by March 31?,will-mrbeast-hit-477-million-subscribers-by-march-31-246-645,0xf5dad4c302a8e5a52730171d0f3928c69982726da53375ddf260e7269df96ae5,48500566029691014494538715409643159805481226449050858904270561683848714742810,2026-03-31T00:00:00Z,9.944768e+03,5175.12810
18,Bank of England decreases interest rates by 25 bps after March 2026 meeting?,bank-of-england-decreases-interest-rates-by-25-bps-after-march-2026-meeting-384,0xb2e1fde8d5b6d178509efb34b3850c69a7bc742c361ba6016054e50302f833c7,22090835838074327391045821864169112707760835582772637183872923635041881148116,2026-03-19T00:00:00Z,9.938091e+03,5790.14630
19,Will Jimmy Butler win the 2025–2026 NBA Clutch Player of the Year?,nba-2025-26-clutch-player-of-the-year-jimmy-butler,0x4d9dc5a7e516dcec935b0381707ccd4c52d1e73fe8d90307ec8309e4728551c8,93287580662612374998000503364773686496854653048711183445257002067443625560147,2026-06-30T00:00:00Z,9.937853e+03,1218.54960

In [5]:
# Top markets across all categories (fallback exploration)
all_df = fetch_all_markets(limit=50)
all_df[["question", "slug", "condition_id", "clob_token_yes", "end_date", "volume", "liquidity", "tags"]].head(20)

INFO:src.client:Saved raw JSON → /Users/hetp/Documents/UWaterloo/4B/SYDE 532/Project/data/raw/markets_all.json

,question,slug,condition_id,clob_token_yes,end_date,volume,liquidity,tags
0,Will Vivek Ramaswamy win the 2028 Republican presidential nomination?,will-vivek-ramaswamy-win-the-2028-republican-presidential-nomination,0xd997dc2a212a7d6673375a3b016db1fb214247142f8cde0cbf07f8e6d789877c,7847177314809025001842027337093046201021185723933452855314998541165696902642,2028-11-07T00:00:00Z,9.897463e+06,538674.00119,
1,Will Delcy Rodríguez be the leader of Venezuela end of 2026?,will-delcy-rodrguez-be-the-leader-of-venezuela-end-of-2026,0xa01d48a973e40770719dab42faf1aeae5da4376d9eca46e77265c7551d1be0f7,38667196958602416137463628517439560119304765709104570192447644733106171420112,2026-12-31T00:00:00Z,9.911145e+05,27597.21430,
2,Will The Weeknd have the greatest number of monthly Spotify listeners this m...,will-the-weeknd-have-the-greatest-number-of-monthly-spotify-listeners-this-m...,0xe8ec9fb94e2c3c30a53bd6cddd5ed0818430576c109028ec04ea6fe47ec16ffd,72215495808962882442227957504397899994205027071946858683339872158649978621745,2026-02-28T00:00:00Z,9.997987e+04,5858.05711,
3,"Grok 5 released by March 31, 2026?",grok-5-released-by-march-31-2026,0xb7b4b48d233d854fa0793bb3ac3da246bd7863e6039300b61df035125fe4f581,111199335102802129986385434826729904605097886098325344211061360860214628320521,NaN,9.987279e+04,8263.88940,
4,Will Silver (SI) hit (HIGH) $185 by end of February?,will-silver-si-hit-high-185-by-end-of-february-694-754,0x8eebd379d1fd9d12f58e0a97c2aae73f1e1fd0c92c31b59275fc3645b1597f87,3132591794760264995577925527621672916339864017285721439131771940573384623848,2026-02-28T00:00:00Z,9.962033e+04,158741.57036,
5,Nuclear weapon detonation by March 31?,nuclear-weapon-detonation-by-march-31,0x4afb076c5d9dfe1c33bf300cfd9fb93a5a8d9bfce8fe2beaeccbde5f8c269fc1,83745161536963539374758363997483220394665712527717501198935570938573276596563,2026-03-31T00:00:00Z,9.932240e+04,8778.14312,
6,Will Japan’s January 2026 unemployment rate be ≤2.1%?,will-japans-january-2026-unemployment-rate-be-2pt1,0xd822ccf5f9325363598c8a47bd8e1f7f5c4ee2bd05106317e1524cc16a3a9f95,84909634827707129486900371878355483917943245288000191120896879062473383973290,2026-03-03T00:00:00Z,9.896720e+04,240.58162,
7,Kings vs. Blue Jackets: O/U 6.5,nhl-lak-cbj-2026-01-26-total-6pt5,0x203511b34fa55670a3d65b460e912652fdd4255258828b266b3da45c84521acf,69506504769963901283918727206455219450062789028070087224654077420495427804288,2026-01-27T00:00:00Z,9.999917e+03,135.84960,
8,Will Morocco win Group C in the 2026 FIFA World Cup?,will-morocco-win-group-c-in-the-2026-fifa-world-cup,0xcd82ced289c1009bb08ea7d74cdc4c56d7e3feaf4eebafa429e04d8d08ba8eb6,9993362623254508594982212570716155560975868718584876749669600087469425428671,2026-06-27T00:00:00Z,9.996884e+03,3427.00730,
9,"Will ""Sinners"" win exactly 5 awards at the Oscars?",will-sinners-win-exactly-5-awards-at-the-oscars,0xad8e66948595968c5eb29fbda0c805ea53a0f45e00310f07b10c7e7681027c04,79490522542250943082390022419364604163533005858719367745573112352656937744621,2026-03-15T00:00:00Z,9.978144e+03,3343.46750,
10,Will CR win the most seats in the 2026 Colombian Chamber of Representatives ...,will-cr-win-the-most-seats-in-the-2026-colombian-chamber-of-representatives-...,0x4a48f9a1e2cd2a274ff636ba53326479cafad09e21ce526aa7b07e3add67575a,69539866920971893324539701255733985995005298853448247993841542507119576740580,2026-03-08T20:00:00Z,9.977751e+03,6163.84350,
11,New Zealand Breakers vs. Cairns Taipans,bknbl-new-cai-2026-02-19,0xe01dfa0612a80d56eae85d911e89cd98cde1d0f6717c0e583b5a6d5a29d4ad64,78892455310794078214292476247012110024049050529854661365916968305741151792952,2026-02-26T06:30:00Z,9.974423e+03,1173.24140,
12,US seizes an Iran-linked oil tanker by Feb 28?,us-seizes-an-iran-linked-oil-tanker-by-feb-28,0xa32bd28c0c288da3ddf21b34f6a86679c2ae81232f03441df6b9eff63d16a6cf,105509773956777725100823655243528621611068096678262325758329096120271236435431,2026-02-28T00:00:00Z,9.961374e+03,3472.30910,
13,Will Janez Janša be the next Prime Minister of Slovenia?,will-janez-jana-be-the-next-prime-minister-of-slovenia,0xe94749bbf616139120735f9720de5b1a94b61cb7da0feb633f97f113d61a167b,82530627405409911305927805635950267430246838540555305041705674192961973127302,2026-03-22T00:00:00Z,9.960947e+03,6489.53840,
14,"Will the US next strike Iran during the week of February 15-21, 2026 (ET)?",will-the-us-next-strike-iran-during-the-week-of-february-15-21-2026-et,0x6395cbd98104c532b1a74470f0f0b2e765ca740bbc623d5f04fbf282e6fe3652,77944431976570712623048042703776067647183345723044716065978734139522523537860,2026-04-04T00:00:00Z,9.958677e+03,3039.13760,
15,Will the Los Angeles Clippers finish as the #1 seed in the 2025–2026 NBA Wes...,will-the-los-angeles-clippers-finish-as-the-1-seed-in-the-20252026-nba-weste...,0xe05794ccced6b2687a43502896ec8bbb1a7efd26f05adc88edc96916a6d92475,103365321044546830351586566069038719229016365199771829748333033747738176327765,2026-04-12T00:00:00Z,9.953652e+03,22078.19736,
16,Will Elon Musk post 1360-1399 tweets in March 2026?,elon-musk-of-tweets-march-2026-1360-1399,0x044f3ae5fdf246b4b5f8ff4233cea15c083932cd019bc25410d027b87a927df7,77834041247353940463018240476424059627370749493122205515409543524601837582710,2026-04-01T04:00:00Z,9.944945e+03,10206.01450,
17,Will MrBeast hit 477 Million subscribers by March 31?,will-mrbeast-hit-477-million-subscribers-by-march-31-246-645,0xf5dad4c302a8e5a52730171d0f3928c69982726da53375ddf260e7269df96ae5,48500566029691014494538715409643159805481226449050858904270561683848714742810,2026-03-31T00:00:00Z,9.944768e+03,5175.12810,
18,Bank of England decreases interest rates by 25 bps after March 2026 meeting?,bank-of-england-decreases-interest-rates-by-25-bps-after-march-2026-meeting-384,0xb2e1fde8d5b6d178509efb34b3850c69a7bc742c361ba6016054e50302f833c7,22090835838074327391045821864169112707760835582772637183872923635041881148116,2026-03-19T00:00:00Z,9.938091e+03,5790.14630,
19,Will Jimmy Butler win the 2025–2026 NBA Clutch Player of the Year?,nba-2025-26-clutch-player-of-the-year-jimmy-butler,0x4d9dc5a7e516dcec935b0381707ccd4c52d1e73fe8d90307ec8309e4728551c8,93287580662612374998000503364773686496854653048711183445257002067443625560147,2026-06-30T00:00:00Z,9.937853e+03,1218.54960,

## 3. Select the triad

Fill in the three selections below using rows from the tables above.

**Selection criteria:**
- **Base**: highest-volume political market with a future end date
- **Similar**: another political market from the same event cluster
- **Dissimilar**: a sports market with different participation characteristics

In [8]:
# ── EDIT THESE after inspecting the tables above ──────────────────────

base = {
    "slug": "will-vivek-ramaswamy-win-the-2028-republican-presidential-nomination",
    "condition_id": "0xd997dc2a212a7d6673375a3b016db1fb214247142f8cde0cbf07f8e6d789877c",
    "clob_token_yes": "7847177314809025001842027337093046201021185723933452855314998541165696902642",
    "end_date": "2028-11-07T00:00:00Z",
    "category": "politics",
    "role": "base",
}

similar = {
    "slug": "will-delcy-rodrguez-be-the-leader-of-venezuela-end-of-2026",
    "condition_id": "0xa01d48a973e40770719dab42faf1aeae5da4376d9eca46e77265c7551d1be0f7",
    "clob_token_yes": "38667196958602416137463628517439560119304765709104570192447644733106171420112",
    "end_date": "2026-12-31T00:00:00Z",
    "category": "politics",
    "role": "similar",
}

dissimilar = {
    "slug": "nba-2025-26-clutch-player-of-the-year-jimmy-butler",
    "condition_id": "0x4d9dc5a7e516dcec935b0381707ccd4c52d1e73fe8d90307ec8309e4728551c8",
    "clob_token_yes": "93287580662612374998000503364773686496854653048711183445257002067443625560147",
    "end_date": "2026-06-30T00:00:00Z",
    "category": "sports",
    "role": "dissimilar",
}

triad = build_triad_config([base, similar, dissimilar])
pd.DataFrame(triad)

,slug,condition_id,clob_token_id,end_date,category,role
0,will-vivek-ramaswamy-win-the-2028-republican-presidential-nomination,0xd997dc2a212a7d6673375a3b016db1fb214247142f8cde0cbf07f8e6d789877c,7847177314809025001842027337093046201021185723933452855314998541165696902642,2028-11-07T00:00:00Z,politics,base
1,will-delcy-rodrguez-be-the-leader-of-venezuela-end-of-2026,0xa01d48a973e40770719dab42faf1aeae5da4376d9eca46e77265c7551d1be0f7,38667196958602416137463628517439560119304765709104570192447644733106171420112,2026-12-31T00:00:00Z,politics,similar
2,nba-2025-26-clutch-player-of-the-year-jimmy-butler,0x4d9dc5a7e516dcec935b0381707ccd4c52d1e73fe8d90307ec8309e4728551c8,93287580662612374998000503364773686496854653048711183445257002067443625560147,2026-06-30T00:00:00Z,sports,dissimilar

## 4. Write triad to config

Run the cell below to persist the selection into `src/config.py`.
All downstream pipeline steps read from there.

In [9]:
import textwrap, pathlib

config_path = pathlib.Path.cwd().parent / "src" / "config.py"
config_text = config_path.read_text()

# Replace the TRIAD_MARKETS list in config.py
import re
new_block = f"TRIAD_MARKETS: list[dict] = {triad!r}\n"
config_text = re.sub(
    r"TRIAD_MARKETS: list\[dict\] = .*?\n(\s*#.*\n)*",
    new_block,
    config_text,
    flags=re.DOTALL,
)
# Also handle the empty-list case
config_text = re.sub(
    r"TRIAD_MARKETS: list\[dict\] = \[\]",
    f"TRIAD_MARKETS: list[dict] = {triad!r}",
    config_text,
)

config_path.write_text(config_text)
print(f"Wrote {len(triad)} triad entries to {config_path}")

Wrote 3 triad entries to /Users/hetp/Documents/UWaterloo/4B/SYDE 532/Project/src/config.py